/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FirstSlide: typeof import('./src/components/FirstSlide.vue')['default']
    FootSlide: typeof import('./src/components/FootSlide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerticalParallaxSwiper: typeof import('./src/components/VerticalParallaxSwiper.vue')['default']
  }
}
